'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Almacen
    Public Property id_almacen As Integer
    Public Property codigo As String
    Public Property nombre As String
    Public Property coeficiente_volumetrico As Double
    Public Property id_cliente As Integer

    Public Overridable Property Cliente As Cliente
    Public Overridable Property Articulo As ICollection(Of Articulo) = New HashSet(Of Articulo)

End Class
