'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Historico
    Public Property id_historico As Integer
    Public Property fecha_transaccion As Date
    Public Property tipo_transaccion As String
    Public Property referencia_ubicacion As String
    Public Property documento_transaccion As String
    Public Property cantidad_transaccion As Double
    Public Property id_articulo As Integer

    Public Overridable Property Articulo As Articulo

End Class
