'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Imagen
    Public Property id_imagen As Integer
    Public Property nombre As String
    Public Property url_imagen As String
    Public Property id_articulo As Integer

    Public Overridable Property Articulo As Articulo

End Class
