'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class LogisPackEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=LogisPackEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property C__MigrationHistory() As DbSet(Of C__MigrationHistory)
    Public Overridable Property Almacen() As DbSet(Of Almacen)
    Public Overridable Property Articulo() As DbSet(Of Articulo)
    Public Overridable Property AspNetRoles() As DbSet(Of AspNetRoles)
    Public Overridable Property AspNetUserClaims() As DbSet(Of AspNetUserClaims)
    Public Overridable Property AspNetUserLogins() As DbSet(Of AspNetUserLogins)
    Public Overridable Property AspNetUsers() As DbSet(Of AspNetUsers)
    Public Overridable Property Cliente() As DbSet(Of Cliente)
    Public Overridable Property Historico() As DbSet(Of Historico)
    Public Overridable Property Imagen() As DbSet(Of Imagen)
    Public Overridable Property Picking_Articulo() As DbSet(Of Picking_Articulo)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property Tipo_Facturacion() As DbSet(Of Tipo_Facturacion)
    Public Overridable Property Tipo_Unidad() As DbSet(Of Tipo_Unidad)
    Public Overridable Property Ubicacion() As DbSet(Of Ubicacion)

End Class
