'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Picking_Articulo
    Public Property id_picking_articulo As Integer
    Public Property unidades As Double
    Public Property id_picking As Integer
    Public Property id_articulo As Integer

    Public Overridable Property Articulo As Articulo
    Public Overridable Property Articulo1 As Articulo

End Class
