'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tipo_Unidad
    Public Property id_tipo_unidad As Integer
    Public Property nombre As String

    Public Overridable Property Articulo As ICollection(Of Articulo) = New HashSet(Of Articulo)

End Class
