'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ubicacion
    Public Property id_ubicacion As Integer
    Public Property zona As String
    Public Property estante As String
    Public Property fila As String
    Public Property columna As String
    Public Property panel As String
    Public Property referencia_ubicacion As String
    Public Property id_articulo As Integer

    Public Overridable Property Articulo As Articulo

End Class
