var btn_acordeon_Index = '.sectionHeaderButtons'
var img_btn_acordeon_Index = '.sectionHeaderButton'
var acordeon_Index = '#sectionContentFiltrosCabecera'
var Hidden_Acordeon_Index = '#MainContent_hfaccordion'

var txtObsGen = 'MainContent_txtObsGen'
var txtObsArt = 'MainContent_txtObsArt'
var txtcount1 = 'count1'
var txtcount2 = 'count2'
var txtalert1 = 'alert1'
var txtalert2 = 'alert2'

var txtZonas = '#MainContent_txtZona'
var txtEstantes = '#MainContent_txtEstante'
var txtFilas = '#MainContent_txtFila'
var txtColumnas = '#MainContent_txtColumna'
var txtPaneles = '#MainContent_txtPanel'